add compact encoding support
creditkarma/thrift-utils pull request #3
Opened 2018-07-17 00:03 UTC by rohan-malpani-ck

Adding compact encoding support by adding a boolean to the existing functions. Could also just create separate functions if you think this is confusing.

2018-07-17 16:49 UTC, kevin-greene-ck requested changes

2018-07-17 16:49 UTC, kevin-greene-ck commented on src/main/codec.ts
> +export const encoder = (thriftObject: StructLike, useCompactProtocol: boolean = false): Promise<Buffer> => {
Talked to you about this in person, just putting here for reference. I'd like to see `useCompactProtocol` actually be replace with the protocol class.

```
export const encoder = (thriftObject: StructLike, protocol: IProtocolConstructor = BinaryProtocol): Promise<Buffer>
```

Also of note, I believe that `thrift-server-core` exports an interface for `IProtocolConstructor`.

2018-07-17 16:49 UTC, kevin-greene-ck commented on src/main/codec.ts
> +export function decoder<T extends StructLike>(buffer: string,
Same change as encode

2018-07-18 18:58 UTC, rohan-malpani-ck commented
Made the changes requested @kevin-greene-ck

2018-07-18 19:00 UTC, kevin-greene-ck approved these changes

2018-07-18 19:00 UTC, merged